# Generated by Django 5.0 on 2025-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
