# Generated by Django 5.0 on 2025-09-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_link_label_alter_link_url_alter_skill_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("JOB_SEEKER", "Job Seeker"), ("RECRUITER", "Recruiter")],
                default="JOB_SEEKER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
