# Generated by Django 5.0 on 2025-10-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('JOB_SEEKER', 'Job Seeker'), ('RECRUITER', 'Recruiter'), ('ADMINISTRATOR', 'Administrator')], default='JOB_SEEKER', max_length=20),
        ),
    ]
