# Generated by Django 5.0 on 2025-10-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Your default resume for one-click applications.",
                null=True,
                upload_to="user_resumes/",
            ),
        ),
    ]
