# Generated by Django 5.0 on 2025-10-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (Visible to everyone)"),
                    (
                        "RECRUITERS",
                        "Recruiters Only (Visible to recruiters and in searches)",
                    ),
                    ("PRIVATE", "Private (Only you can see it)"),
                ],
                default="RECRUITERS",
                max_length=20,
            ),
        ),
    ]
