# Generated by Django 5.0 on 2025-10-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="visibility",
        ),
        migrations.AddField(
            model_name="profile",
            name="education_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (Visible to everyone)"),
                    ("RECRUITERS", "Recruiters Only"),
                    ("PRIVATE", "Private (Only you can see it)"),
                ],
                default="RECRUITERS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (Visible to everyone)"),
                    ("RECRUITERS", "Recruiters Only"),
                    ("PRIVATE", "Private (Only you can see it)"),
                ],
                default="RECRUITERS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="links_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (Visible to everyone)"),
                    ("RECRUITERS", "Recruiters Only"),
                    ("PRIVATE", "Private (Only you can see it)"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (Visible to everyone)"),
                    ("RECRUITERS", "Recruiters Only"),
                    ("PRIVATE", "Private (Only you can see it)"),
                ],
                default="RECRUITERS",
                help_text="Controls visibility of the resume download link on your profile.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (Visible to everyone)"),
                    ("RECRUITERS", "Recruiters Only"),
                    ("PRIVATE", "Private (Only you can see it)"),
                ],
                default="RECRUITERS",
                max_length=20,
            ),
        ),
    ]
