# Generated by Django 5.0 on 2025-10-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_profile_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
