# Generated by Django 5.0 on 2025-09-25 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns/manages this company (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
