# Generated by Django 5.0 on 2025-10-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_company_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="cover_letter",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="A brief note to the recruiter explaining why you're a great fit for this role.",
                verbose_name="Tailored Note",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
    ]
