# Generated by Django 5.0 on 2025-10-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_jobapplication_cover_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("SCREENING", "Screening"),
                    ("INTERVIEW", "Interview"),
                    ("OFFER", "Offer"),
                    ("HIRED", "Hired"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
