# Generated by Django 5.0 on 2025-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_jobapplication_resume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
