# Generated by Django 5.2.7 on 2025-10-25 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_job_latitude_job_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('search_query', models.CharField(blank=True, help_text='Keywords to search for', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Location filter', max_length=200)),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('remote', 'Remote'), ('internship', 'Internship')], help_text='Job type filter', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], help_text='Experience level filter', max_length=20)),
                ('salary_range', models.CharField(blank=True, help_text='Salary range filter', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to send notifications for this search')),
                ('last_notified', models.DateTimeField(blank=True, help_text='Last time notifications were sent', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(help_text='The recruiter who created this search', on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'recruiter')},
            },
        ),
    ]
