# Generated by Django 5.2.7 on 2025-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_savedsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='search_query',
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='current_company',
            field=models.CharField(blank=True, help_text='Current company filter', max_length=200),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='education_level',
            field=models.CharField(blank=True, help_text='Education level filter', max_length=100),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='experience_years',
            field=models.CharField(blank=True, help_text='Years of experience filter', max_length=20),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='skills_query',
            field=models.CharField(blank=True, help_text='Skills to search for (comma-separated)', max_length=500),
        ),
    ]
